In [13]:
import pandas as pd

In [50]:
df = pd.read_csv('P1.csv')
df.head()

         Date Security   Action  Quantity
0  2019-10-31      MMM  Deposit         1
1  2019-11-01      ABT  Deposit         2
2  2019-11-02     ABBV      Buy         3
3  2019-11-03     ABMD      Buy         4
4  2019-11-04      ACN      Buy         1

In [51]:
import yfinance as yf  

data = yf.download('AAPL','2019-10-31','2019-10-31')
print(data['Close'][0])

prices = []

for index, row in df.iterrows():
    print(row['Security'] + ' ' + row['Date'])    
    data = yf.download(row['Security'],row['Date'],row['Date'])    
    if data.empty:
        #print("An exception occurred")
        prices.append(0)
    else:
        #print(data)
        prices.append(round(data['Close'][0], 2))

[*********************100%***********************]  1 of 1 completed
60.814998626708984
MMM 2019-10-31
[*********************100%***********************]  1 of 1 completed
ABT 2019-11-01
[*********************100%***********************]  1 of 1 completed
ABBV 2019-11-02
[*********************100%***********************]  1 of 1 completed
ABMD 2019-11-03
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ABMD: No data found for this date range, symbol may be delisted
ACN 2019-11-04
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ACN: No data found for this date range, symbol may be delisted
ATVI 2019-11-05
[*********************100%***********************]  1 of 1 completed
ADBE 2019-11-06
[*********************100%***********************]  1 of 1 completed
AMD 2019-11-07
[*********************100%***********************]  1 of 1 completed
AAP 2019-11-08
[*********************100%***********************]  1 of 1 completed
AES 2019-11-09
[*********************100%***********************]  1 of 1 completed
AFL 2019-11-10
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- AFL: No data found for this date range, symbol may be delisted
A 2019-11-11
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- A: No data found for this date range, symbol may be delisted
APD 2019-11-12
[*********************100%***********************]  1 of 1 completed
AKAM 2019-11-13
[*********************100%***********************]  1 of 1 completed
ALK 2019-11-14
[*********************100%***********************]  1 of 1 completed
ALB 2019-11-15
[*********************100%***********************]  1 of 1 completed
ARE 2019-11-16
[*********************100%***********************]  1 of 1 completed
ALXN 2019-11-17
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ALXN: No data found for this date range, symbol may be delisted
ALGN 2019-11-18
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ALGN: No data found for this date range, symbol may be delisted
ALLE 2019-11-19
[*********************100%***********************]  1 of 1 completed
LNT 2019-11-20
[*********************100%***********************]  1 of 1 completed
ALL 2019-11-21
[*********************100%***********************]  1 of 1 completed
GOOGL 2019-11-22
[*********************100%***********************]  1 of 1 completed
GOOG 2019-11-23
[*********************100%***********************]  1 of 1 completed
MO 2019-11-24
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- MO: No data found for this date range, symbol may be delisted
AMZN 2019-11-25
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- AMZN: No data found for this date range, symbol may be delisted
AMCR 2019-11-26
[*********************100%***********************]  1 of 1 completed
AEE 2019-11-27
[*********************100%***********************]  1 of 1 completed
AAL 2019-11-28
[*********************100%***********************]  1 of 1 completed
AEP 2019-11-29
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- AEP: No data found for this date range, symbol may be delisted
AXP 2019-11-30
[*********************100%***********************]  1 of 1 completed

In [52]:
print(type(prices))
df['Price'] = prices

df['Total'] = df['Price'] * df['Quantity']

<class 'list'>

          Date Security   Action  Quantity    Price     Total
0   2019-10-31      MMM  Deposit         1   168.37    168.37
1   2019-11-01      ABT  Deposit         2    83.61    167.22
2   2019-11-02     ABBV      Buy         3    81.75    245.25
3   2019-11-03     ABMD      Buy         4     0.00      0.00
4   2019-11-04      ACN      Buy         1     0.00      0.00
5   2019-11-05     ATVI  Deposit         5    55.71    278.55
6   2019-11-06     ADBE      Buy        10   289.29   2892.90
7   2019-11-07      AMD  Deposit        23    35.93    826.39
8   2019-11-08      AAP  Deposit        46   169.28   7786.88
9   2019-11-09      AES  Deposit        63    17.64   1111.32
10  2019-11-10      AFL      Buy        56     0.00      0.00
11  2019-11-11        A      Buy        39     0.00      0.00
12  2019-11-12      APD      Buy        81   235.03  19037.43
13  2019-11-13     AKAM  Deposit        64    84.72   5422.08
14  2019-11-14      ALK      Buy        23    70.52   1621.96
15  2019-11-15      ALB  Deposit        14    65.54    917.56
16  2019-11-16      ARE  Deposit        77   158.76  12224.52
17  2019-11-17     ALXN  Deposit        95     0.00      0.00
18  2019-11-18     ALGN      Buy        46     0.00      0.00
19  2019-11-19     ALLE      Buy        32   118.41   3789.12
20  2019-11-20      LNT      Buy        57    52.58   2997.06
21  2019-11-21      ALL  Deposit         4   110.40    441.60
22  2019-11-22    GOOGL      Buy        18  1300.14  23402.52
23  2019-11-23     GOOG  Deposit        46  1295.34  59585.64
24  2019-11-24       MO  Deposit        60     0.00      0.00
25  2019-11-25     AMZN  Deposit        19     0.00      0.00
26  2019-11-26     AMCR      Buy        91    10.11    920.01
27  2019-11-27      AEE      Buy        26    74.13   1927.38
28  2019-11-28      AAL      Buy        28    28.95    810.60
29  2019-11-29      AEP  Deposit        40     0.00      0.00
30  2019-11-30      AXP      Buy        31   120.12   3723.72

In [53]:
df= df[df['Price'] != 0]
df

          Date Security   Action  Quantity    Price     Total
0   2019-10-31      MMM  Deposit         1   168.37    168.37
1   2019-11-01      ABT  Deposit         2    83.61    167.22
2   2019-11-02     ABBV      Buy         3    81.75    245.25
5   2019-11-05     ATVI  Deposit         5    55.71    278.55
6   2019-11-06     ADBE      Buy        10   289.29   2892.90
7   2019-11-07      AMD  Deposit        23    35.93    826.39
8   2019-11-08      AAP  Deposit        46   169.28   7786.88
9   2019-11-09      AES  Deposit        63    17.64   1111.32
12  2019-11-12      APD      Buy        81   235.03  19037.43
13  2019-11-13     AKAM  Deposit        64    84.72   5422.08
14  2019-11-14      ALK      Buy        23    70.52   1621.96
15  2019-11-15      ALB  Deposit        14    65.54    917.56
16  2019-11-16      ARE  Deposit        77   158.76  12224.52
19  2019-11-19     ALLE      Buy        32   118.41   3789.12
20  2019-11-20      LNT      Buy        57    52.58   2997.06
21  2019-11-21      ALL  Deposit         4   110.40    441.60
22  2019-11-22    GOOGL      Buy        18  1300.14  23402.52
23  2019-11-23     GOOG  Deposit        46  1295.34  59585.64
26  2019-11-26     AMCR      Buy        91    10.11    920.01
27  2019-11-27      AEE      Buy        26    74.13   1927.38
28  2019-11-28      AAL      Buy        28    28.95    810.60
30  2019-11-30      AXP      Buy        31   120.12   3723.72

In [54]:
df = df.round(2)
df.to_csv('Portfolio1.csv', index = False)